# Generated by Django 3.1.7 on 2021-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webanalysis',
            name='page_content_type',
            field=models.CharField(default='text/plain', max_length=30),
            preserve_default=False,
        ),
    ]
